apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-sa
      containers:
        - name: watcher
          image: auto-healing-watcher:v2
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "128Mi"
